name: Weekly Notebook Run

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v3

    - name: Python installieren
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Abhängigkeiten installieren
      run: |
        pip install -r requirements.txt
        pip install papermill ipykernel

    - name: Notebook ausführen
      run: |
        papermill Datenaufbereitung.ipynb ausgegebenes_notebook.ipynb

    - name: Matplotlib-Diagramme als Artefakte speichern
      uses: actions/upload-artifact@v4
      with:
        name: matplotlib-diagramme
        path: |
          Jahresübersicht.html
          Umsatzstärkstes_Quartal.html
          Quartalsübersicht.html
          Umsatzstärkster_Monat.html
          Monatsübersicht.html
          Umsatzstärkster_Verkaufskanal.html
          Umsatzstärkster_Verkaufskanal_pro_Jahr.html
          Umsatzstärkste_Ausstellung.html
          Jahresübersicht_mobile.html
          Umsatzstärkster_Verkaufskanal_mobile.html
          Umsatzstärkste_Ausstellung mobile.html

    - name: Änderungen committen und pushen
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add Jahresübersicht.html Umsatzstärkstes_Quartal.html Quartalsübersicht.html Umsatzstärkster_Monat.html Monatsübersicht.html Umsatzstärkster_Verkaufskanal.html Umsatzstärkster_Verkaufskanal_pro_Jahr.html Umsatzstärkste_Ausstellung.html Jahresübersicht_mobile.html Umsatzstärkster_Verkaufskanal_mobile.html Umsatzstärkste_Ausstellung_mobile.html
        git commit -m "Diagramme für GitHub Pages aktualisiert" || echo "Keine Änderungen zum Commit"
        git push

